"""Add recipe models

Revision ID: 006ba2cb531e
Revises: 396e88ed1f2f
Create Date: 2026-08-18 13:34:09.557497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006ba2cb531e'
down_revision = '396e88ed1f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('instructions_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('external_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_cuisine'), ['cuisine'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_recipes_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_total_time_minutes'), ['total_time_minutes'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_text', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_unit_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_ingredient_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_total_time_minutes'))
        batch_op.drop_index(batch_op.f('ix_recipes_source_type'))
        batch_op.drop_index(batch_op.f('ix_recipes_source_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_public_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_is_active'))
        batch_op.drop_index(batch_op.f('ix_recipes_household_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_difficulty'))
        batch_op.drop_index(batch_op.f('ix_recipes_cuisine'))
        batch_op.drop_index(batch_op.f('ix_recipes_category'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
