"""Add ingredient substitutions

Revision ID: 0dbf7b43be94
Revises: 6568f04da5a5
Create Date: 2026-08-17 09:39:35.063394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf7b43be94'
down_revision = '6568f04da5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('source_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('target_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('quantity_ratio', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('context', sa.String(length=40), nullable=False),
    sa.Column('note_hu', sa.Text(), nullable=True),
    sa.Column('note_en', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ingredient_id', 'target_ingredient_id', 'context', name='uq_ingredient_substitution')
    )
    with op.batch_alter_table('ingredient_substitutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_substitutions_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_substitutions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingredient_substitutions_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_substitutions_source_ingredient_id'), ['source_ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_substitutions_target_ingredient_id'), ['target_ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_substitutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_substitutions_target_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_substitutions_source_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_substitutions_rating'))
        batch_op.drop_index(batch_op.f('ix_ingredient_substitutions_public_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_substitutions_context'))

    op.drop_table('ingredient_substitutions')
    # ### end Alembic commands ###
