"""Add inventory batches

Revision ID: 11dee1e653f7
Revises: 1760272cd2d1
Create Date: 2026-08-17 09:51:16.624221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dee1e653f7'
down_revision = '1760272cd2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_batches_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_storage_location_id'), ['storage_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_unit_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_storage_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_public_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_is_active'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_household_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiration_date'))

    op.drop_table('inventory_batches')
    # ### end Alembic commands ###
