"""Add storage locations and products

Revision ID: 1760272cd2d1
Revises: 0dbf7b43be94
Create Date: 2026-08-17 09:46:16.764371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1760272cd2d1'
down_revision = '0dbf7b43be94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location_type', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'parent_id', 'name', name='uq_storage_location_name')
    )
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_locations_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_locations_location_type'), ['location_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_locations_public_id'), ['public_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('package_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('package_unit_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_package_unit_id'), ['package_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_public_id'), ['public_id'], unique=True)

    op.create_table('product_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('barcode_type', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_product_barcode')
    )
    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_barcodes_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_barcodes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_barcodes_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_barcodes_source'))
        batch_op.drop_index(batch_op.f('ix_product_barcodes_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_barcodes_barcode'))

    op.drop_table('product_barcodes')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_public_id'))
        batch_op.drop_index(batch_op.f('ix_products_package_unit_id'))
        batch_op.drop_index(batch_op.f('ix_products_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_products_household_id'))

    op.drop_table('products')
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_locations_public_id'))
        batch_op.drop_index(batch_op.f('ix_storage_locations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_storage_locations_location_type'))
        batch_op.drop_index(batch_op.f('ix_storage_locations_household_id'))

    op.drop_table('storage_locations')
    # ### end Alembic commands ###
