"""Add product metadata

Revision ID: 396e88ed1f2f
Revises: 9aa66c186636
Create Date: 2026-08-18 09:52:30.382278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396e88ed1f2f'
down_revision = '9aa66c186636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_hu', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('generic_name_hu', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('generic_name_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ingredients_text_hu', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingredients_text_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('external_source', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('external_source_id', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('external_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_external_source'), ['external_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_external_source_id'), ['external_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_external_source_id'))
        batch_op.drop_index(batch_op.f('ix_products_external_source'))
        batch_op.drop_column('external_data')
        batch_op.drop_column('external_source_id')
        batch_op.drop_column('external_source')
        batch_op.drop_column('ingredients_text_en')
        batch_op.drop_column('ingredients_text_hu')
        batch_op.drop_column('generic_name_en')
        batch_op.drop_column('generic_name_hu')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_hu')

    # ### end Alembic commands ###
