"""Add storage location images

Revision ID: 5c6634fb8009
Revises: 8f6a3dbf85c8
Create Date: 2026-08-23 08:37:31.128326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6634fb8009'
down_revision = '8f6a3dbf85c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_location_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_location_id', 'stored_filename', name='uq_storage_location_image_file')
    )
    with op.batch_alter_table('storage_location_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_location_images_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_storage_location_images_storage_location_id'), ['storage_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_location_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_location_images_storage_location_id'))
        batch_op.drop_index(batch_op.f('ix_storage_location_images_public_id'))

    op.drop_table('storage_location_images')
    # ### end Alembic commands ###
