"""Increase unit conversion precision

Revision ID: 6568f04da5a5
Revises: 66872646d5b1
Create Date: 2026-08-17 09:23:06.128449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6568f04da5a5'
down_revision = '66872646d5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('factor_to_base',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Numeric(precision=24, scale=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('factor_to_base',
               existing_type=sa.Numeric(precision=24, scale=12),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)

    # ### end Alembic commands ###
