"""Add ingredient master data model

Revision ID: 8cad6df23e0d
Revises: eaafba1448f6
Create Date: 2026-08-17 08:17:38.094188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cad6df23e0d'
down_revision = 'eaafba1448f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ingredient_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_categories_canonical_key'), ['canonical_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingredient_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_categories_public_id'), ['public_id'], unique=True)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_units_dimension'), ['dimension'], unique=False)

    op.create_table('ingredient_category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_code', name='uq_ingredient_category_translation')
    )
    with op.batch_alter_table('ingredient_category_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_category_translations_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_category_translations_language_code'), ['language_code'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default_unit_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['default_unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_canonical_key'), ['canonical_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingredients_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_default_unit_id'), ['default_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_public_id'), ['public_id'], unique=True)

    op.create_table('unit_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'language_code', name='uq_unit_translation')
    )
    with op.batch_alter_table('unit_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_translations_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_translations_unit_id'), ['unit_id'], unique=False)

    op.create_table('ingredient_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalized_alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'language_code', 'normalized_alias', name='uq_ingredient_alias')
    )
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_aliases_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_aliases_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_aliases_normalized_alias'), ['normalized_alias'], unique=False)

    op.create_table('ingredient_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'language_code', name='uq_ingredient_translation')
    )
    with op.batch_alter_table('ingredient_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_translations_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_translations_language_code'), ['language_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_translations_language_code'))
        batch_op.drop_index(batch_op.f('ix_ingredient_translations_ingredient_id'))

    op.drop_table('ingredient_translations')
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_aliases_normalized_alias'))
        batch_op.drop_index(batch_op.f('ix_ingredient_aliases_language_code'))
        batch_op.drop_index(batch_op.f('ix_ingredient_aliases_ingredient_id'))

    op.drop_table('ingredient_aliases')
    with op.batch_alter_table('unit_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_translations_unit_id'))
        batch_op.drop_index(batch_op.f('ix_unit_translations_language_code'))

    op.drop_table('unit_translations')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_public_id'))
        batch_op.drop_index(batch_op.f('ix_ingredients_default_unit_id'))
        batch_op.drop_index(batch_op.f('ix_ingredients_category_id'))
        batch_op.drop_index(batch_op.f('ix_ingredients_canonical_key'))

    op.drop_table('ingredients')
    with op.batch_alter_table('ingredient_category_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_category_translations_language_code'))
        batch_op.drop_index(batch_op.f('ix_ingredient_category_translations_category_id'))

    op.drop_table('ingredient_category_translations')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_dimension'))
        batch_op.drop_index(batch_op.f('ix_units_code'))

    op.drop_table('units')
    with op.batch_alter_table('ingredient_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_categories_public_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_categories_canonical_key'))

    op.drop_table('ingredient_categories')
    # ### end Alembic commands ###
