"""Add ingredient unit mappings

Revision ID: 8ee3cd9cd9aa
Revises: a7a801aac76a
Create Date: 2026-08-17 10:43:13.475043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee3cd9cd9aa'
down_revision = 'a7a801aac76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'unit_id', name='uq_ingredient_unit')
    )
    with op.batch_alter_table('ingredient_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_units_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_units_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_units_unit_id'))
        batch_op.drop_index(batch_op.f('ix_ingredient_units_ingredient_id'))

    op.drop_table('ingredient_units')
    # ### end Alembic commands ###
