"""Add recipe images

Revision ID: 8f6a3dbf85c8
Revises: ba81a263ed00
Create Date: 2026-08-19 06:57:50.799379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6a3dbf85c8'
down_revision = 'ba81a263ed00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'stored_filename', name='uq_recipe_image_file')
    )
    with op.batch_alter_table('recipe_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_images_is_cover'), ['is_cover'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_images_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_recipe_images_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_images_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_images_public_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_images_is_cover'))

    op.drop_table('recipe_images')
    # ### end Alembic commands ###
