"""Add product images

Revision ID: 9aa66c186636
Revises: 8ee3cd9cd9aa
Create Date: 2026-08-18 07:13:34.378895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa66c186636'
down_revision = '8ee3cd9cd9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'stored_filename', name='uq_product_image_file')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_is_cover'), ['is_cover'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_images_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_public_id'))
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_images_is_cover'))

    op.drop_table('product_images')
    # ### end Alembic commands ###
