"""Add inventory movements

Revision ID: a7a801aac76a
Revises: cf964c9d256f
Create Date: 2026-08-17 09:57:12.147248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a801aac76a'
down_revision = 'cf964c9d256f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('inventory_batch_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_inventory_batch_id'), ['inventory_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_movements_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_unit_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_public_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_inventory_batch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_household_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
