"""Add recipe tags

Revision ID: ba81a263ed00
Revises: 006ba2cb531e
Create Date: 2026-08-18 14:07:12.581605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba81a263ed00'
down_revision = '006ba2cb531e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_tag_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_tag_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_tag_definitions_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_tag_definitions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_tag_definitions_key'), ['key'], unique=True)

    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['recipe_tag_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    recipe_tag_definitions = sa.table(
        "recipe_tag_definitions",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("group_name", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )

    op.bulk_insert(
        recipe_tag_definitions,
        [
            {
                "key": "meat_dish",
                "name": "Húsétel",
                "group_name": "food_type",
                "sort_order": 10,
                "is_active": True,
            },
            {
                "key": "pasta_dish",
                "name": "Tésztaétel",
                "group_name": "food_type",
                "sort_order": 20,
                "is_active": True,
            },
            {
                "key": "soup",
                "name": "Leves",
                "group_name": "food_type",
                "sort_order": 30,
                "is_active": True,
            },
            {
                "key": "main_course",
                "name": "Főétel",
                "group_name": "food_type",
                "sort_order": 40,
                "is_active": True,
            },
            {
                "key": "side_dish",
                "name": "Köret",
                "group_name": "food_type",
                "sort_order": 50,
                "is_active": True,
            },
            {
                "key": "salad",
                "name": "Saláta",
                "group_name": "food_type",
                "sort_order": 60,
                "is_active": True,
            },
            {
                "key": "dessert",
                "name": "Desszert",
                "group_name": "food_type",
                "sort_order": 70,
                "is_active": True,
            },
            {
                "key": "breakfast",
                "name": "Reggeli",
                "group_name": "food_type",
                "sort_order": 80,
                "is_active": True,
            },

            {
                "key": "hungarian",
                "name": "Magyar",
                "group_name": "cuisine",
                "sort_order": 10,
                "is_active": True,
            },
            {
                "key": "italian",
                "name": "Olasz",
                "group_name": "cuisine",
                "sort_order": 20,
                "is_active": True,
            },
            {
                "key": "indian",
                "name": "Indiai",
                "group_name": "cuisine",
                "sort_order": 30,
                "is_active": True,
            },
            {
                "key": "mexican",
                "name": "Mexikói",
                "group_name": "cuisine",
                "sort_order": 40,
                "is_active": True,
            },
            {
                "key": "chinese",
                "name": "Kínai",
                "group_name": "cuisine",
                "sort_order": 50,
                "is_active": True,
            },
            {
                "key": "japanese",
                "name": "Japán",
                "group_name": "cuisine",
                "sort_order": 60,
                "is_active": True,
            },
            {
                "key": "mediterranean",
                "name": "Mediterrán",
                "group_name": "cuisine",
                "sort_order": 70,
                "is_active": True,
            },
            {
                "key": "american",
                "name": "Amerikai",
                "group_name": "cuisine",
                "sort_order": 80,
                "is_active": True,
            },

            {
                "key": "vegetarian",
                "name": "Vegetáriánus",
                "group_name": "diet",
                "sort_order": 10,
                "is_active": True,
            },
            {
                "key": "vegan",
                "name": "Vegán",
                "group_name": "diet",
                "sort_order": 20,
                "is_active": True,
            },
            {
                "key": "gluten_free",
                "name": "Gluténmentes",
                "group_name": "diet",
                "sort_order": 30,
                "is_active": True,
            },
            {
                "key": "lactose_free",
                "name": "Laktózmentes",
                "group_name": "diet",
                "sort_order": 40,
                "is_active": True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tags')
    with op.batch_alter_table('recipe_tag_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_tag_definitions_key'))
        batch_op.drop_index(batch_op.f('ix_recipe_tag_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_recipe_tag_definitions_group_name'))

    op.drop_table('recipe_tag_definitions')
    # ### end Alembic commands ###
