"""Add stock rules

Revision ID: cf964c9d256f
Revises: 11dee1e653f7
Create Date: 2026-08-17 09:54:13.879074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf964c9d256f'
down_revision = '11dee1e653f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('minimum_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'ingredient_id', name='uq_stock_rule_household_ingredient')
    )
    with op.batch_alter_table('stock_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_rules_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_rules_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_rules_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_rules_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_rules_unit_id'))
        batch_op.drop_index(batch_op.f('ix_stock_rules_public_id'))
        batch_op.drop_index(batch_op.f('ix_stock_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_stock_rules_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_stock_rules_household_id'))

    op.drop_table('stock_rules')
    # ### end Alembic commands ###
